In [1]:
import numpy as np

In [3]:
lista = [1, 2, 3, 4, 5]

In [6]:
lista[3]

4

In [8]:
vetor = np.array([1, 2, 3, 4, 5])

In [10]:
type(vetor)

numpy.ndarray

In [11]:
classes = ["pet", "tecnologia", "alimentação"]

In [44]:
classes[0]

'pet'

In [17]:
embeddings = {
    # Pet
    "gato":        np.array([0.9, 0.0, 0.1]),
    "cachorro":    np.array([0.9, 0.0, 0.1]),
    "felino":      np.array([0.9, 0.0, 0.0]),
    
    # Tecnologia
    "robo":        np.array([0.1, 0.9, 0.0]),
    "computador":  np.array([0.0, 0.9, 0.0]),
    "dados":       np.array([0.0, 0.8, 0.1]),
    "algoritmo":   np.array([0.0, 0.95, 0.0]),
    
    # Alimentação
    "racao":       np.array([0.6, 0.0, 0.8]),
    "carne":       np.array([0.0, 0.0, 0.9]),
    "comida":      np.array([0.1, 0.0, 0.9]),
    "bife":        np.array([0.0, 0.0, 0.95]),
}

In [60]:
pergunta = "O cachorro corre atrás do gato, come racao e se alimenta de carne e comida"


In [61]:
tokens = pergunta.lower().split()

In [62]:
tokens

['o',
 'cachorro',
 'corre',
 'atrás',
 'do',
 'gato,',
 'come',
 'racao',
 'e',
 'se',
 'alimenta',
 'de',
 'carne',
 'e',
 'comida']

In [63]:
vetores = [embeddings[token] for token in tokens if token in embeddings]

In [64]:
vetores

[array([0.9, 0. , 0.1]),
 array([0.6, 0. , 0.8]),
 array([0. , 0. , 0.9]),
 array([0.1, 0. , 0.9])]

In [65]:
palavras_encontradas = [token for token in tokens if token in embeddings]

In [66]:
palavras_encontradas


['cachorro', 'racao', 'carne', 'comida']

In [77]:
vetor_media = np.mean(vetores, axis=0)

In [78]:
vetor_media

array([0.4  , 0.   , 0.675])

In [79]:
indice_vencedor = np.argmax(vetor_media)

In [80]:
indice_vencedor

np.int64(2)

In [81]:
tema = classes[indice_vencedor]
tema

'alimentação'

In [82]:
print (f"A pergunta '{pergunta}")
print (f"a palavra encontrada foi: '{palavras_encontradas}'")
print (f"O Tema da pergunta é: '{tema}'")

A pergunta 'O cachorro corre atrás do gato, come racao e se alimenta de carne e comida
a palavra encontrada foi: '['cachorro', 'racao', 'carne', 'comida']'
O Tema da pergunta é: 'alimentação'
