In [3]:
import numpy as np

In [4]:
vetor = np.array([1, 2, 3, 4,5])

In [5]:
vetor

array([1, 2, 3, 4, 5])

In [6]:
type (vetor)

numpy.ndarray

In [8]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
matriz = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 0]])

In [14]:
matriz

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 0]])

In [15]:
type (vetor)

numpy.ndarray

In [22]:
tensor = np.array ([[[1,2], [3 ,4]], [[5,6], [7,8]]])

In [23]:
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])