In [1]:
import numpy as np
import pandas as pd


In [2]:
vetor = np.array([1, 2, 3, 4,5])

In [18]:
vetor

array([1, 2, 3, 4, 5])

In [15]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
tensor = np.array ([[[1,2], [3 ,4]], [[5,6], [7,8]]])

In [20]:
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
tensor.shape

(2, 2, 2)

In [7]:
matriz.shape

(2, 3)

In [9]:
tensor.ndim

3

In [10]:
vetor.size

5

In [17]:
vetor.shape

(5,)

In [16]:
matriz.size

9

In [23]:
vetor.dtype
# inteiro 64 bits ocupa espaço na memoria
# float numeros continuos ex. 1.3 

dtype('int64')

In [28]:
vetor = np.array([1.2, 2.3, 3.4, 4.5, 5.6])

In [25]:
vetor.dtype

dtype('float64')

In [27]:
vetor [1]

np.float64(2.3)

In [29]:
vetor[0:3]
# o terceiro elemento não entra

array([1.2, 2.3, 3.4])

In [37]:
vetor = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [38]:
vetor[0:10:2]
# de 2 em 2 o vetor todo

array([1, 3, 5, 7, 9])

In [46]:
novo_vetor = vetor[0:10:3]
# altera o vetor original. para não alterar tem que usar .copy no final???????

In [47]:
vetor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
novo_vetor

array([ 1,  4,  7, 10])