In [40]:
import numpy as np

In [41]:
vetor = np.array([1, 2, 3, 4, 5])

In [42]:
vetor

array([1, 2, 3, 4, 5])

In [43]:
type (vetor) #tipo de variável

numpy.ndarray

In [44]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #[] para cada linha da matriz

In [45]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
type (matriz)

numpy.ndarray

In [47]:
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) #matriz de n dimensões

In [48]:
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
a = ([1, 2, 3, 4, 5])

In [ ]:
b = a #Com este comando, cada alteração na variável original vai alterar a cópia

In [51]:
a

[1, 2, 3, 4, 5]

In [52]:
b

[1, 2, 3, 4, 5]

In [53]:
a[0] = 10

In [54]:
a

[10, 2, 3, 4, 5]

In [55]:
b

[10, 2, 3, 4, 5]

In [56]:
a

[10, 2, 3, 4, 5]

In [ ]:
b = a.copy() #cópia que não vai ser alterada se alterar a variável original

In [58]:
b

[10, 2, 3, 4, 5]

In [59]:
a[1] = 8

In [60]:
b

[10, 2, 3, 4, 5]

In [61]:
a

[10, 8, 3, 4, 5]

In [ ]:
vetor.shape #quantidade de linhas e colunas da variável

(5,)

In [63]:
matriz.shape

(3, 3)

In [64]:
tensor.shape

(2, 2, 2)

In [ ]:
vetor.size #quantidade de elementos na variável

5

In [66]:
matriz.size

9

In [67]:
tensor.size

8

In [ ]:
vetor.dtype #tipo de número

dtype('int64')

In [69]:
vetor2.dtype

NameError: name 'vetor2' is not defined