<a href="https://colab.research.google.com/github/flaviocrispin/tecnica_programacao/blob/colaborador%2FPedroCarvalho/exercicio1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lista = [1, 2, 3, 4, 5]

In [ ]:
lista[3]

4

In [ ]:
vetor = np.array([1, 2, 3, 4, 5])

In [ ]:
type(vetor)

numpy.ndarray

In [ ]:
classes = ["pet", "tecnologia", "alimentação"]

In [ ]:
classes[0]

'pet'

In [ ]:
embeddings = {

    "gato":        np.array([0.9, 0.0, 0.1]),
    "cachorro":    np.array([0.9, 0.0, 0.1]),
    "felino":      np.array([0.9, 0.0, 0.0]),


    "robo":        np.array([0.1, 0.9, 0.0]),
    "computador":  np.array([0.0, 0.9, 0.0]),
    "dados":       np.array([0.0, 0.8, 0.1]),
    "algoritmo":   np.array([0.0, 0.95, 0.0]),

    "racao":       np.array([0.6, 0.0, 0.8]),
    "carne":       np.array([0.0, 0.0, 0.9]),
    "comida":      np.array([0.1, 0.0, 0.9]),
    "bife":        np.array([0.0, 0.0, 0.95]),
}

In [ ]:
pergunta = "O cachorro corre atrás do gato, come racao e se alimenta de carne e comida"


In [ ]:
tokens = pergunta.lower().split()

In [ ]:
tokens

['o',
 'cachorro',
 'corre',
 'atrás',
 'do',
 'gato,',
 'come',
 'racao',
 'e',
 'se',
 'alimenta',
 'de',
 'carne',
 'e',
 'comida']

In [ ]:
vetores = [embeddings[token] for token in tokens if token in embeddings]

In [ ]:
vetores

[array([0.9, 0. , 0.1]),
 array([0.6, 0. , 0.8]),
 array([0. , 0. , 0.9]),
 array([0.1, 0. , 0.9])]

In [ ]:
palavras_encontradas = [token for token in tokens if token in embeddings]

In [ ]:
palavras_encontradas


['cachorro', 'racao', 'carne', 'comida']

In [ ]:
vetor_media = np.mean(vetores, axis=0)

In [ ]:
vetor_media

array([0.4  , 0.   , 0.675])

In [ ]:
indice_vencedor = np.argmax(vetor_media)

In [ ]:
indice_vencedor

np.int64(2)

In [ ]:
tema = classes[indice_vencedor]
tema

'alimentação'

In [ ]:
print (f"A pergunta '{pergunta}")
print (f"a palavra encontrada foi: '{palavras_encontradas}'")
print (f"O Tema da pergunta é: '{tema}'")

A pergunta 'O cachorro corre atrás do gato, come racao e se alimenta de carne e comida
a palavra encontrada foi: '['cachorro', 'racao', 'carne', 'comida']'
O Tema da pergunta é: 'alimentação'
