In [77]:
import numpy as np

In [78]:
vetor = np.array([1, 2, 3, 4, 5])

In [79]:
prioridade = ["baixa", "media", "alta"]

In [80]:
embeddings = {
    # Baixa Prioridade
    "feio":          np.array([0.91, 0.51, 0.01]),
    "demora":        np.array([0.92, 0.52, 0.02]),
    "desalinhado":   np.array([0.93, 0.53, 0.03]),
    
    # Media Prioridade
    "reiniciar":     np.array([0.01, 0.91, 0.51]),
    "update":        np.array([0.02, 0.92, 0.52]),
    "senha":         np.array([0.03, 0.93, 0.53]),
    "instabilidade": np.array([0.04, 0.94, 0.54]),
    
    # Alta Prioridade
    "travado":       np.array([0.51, 0.01, 0.91]),
    "corrompido":    np.array([0.52, 0.02, 0.92]),
    "pagamento":     np.array([0.53, 0.03, 0.93]),
    "indisponível":  np.array([0.54, 0.04, 0.94]),
}

In [94]:
chamado = "Não consigo alterar minha senha , o computador esta travado , preciso reiniciar ?"


In [95]:
tokens = chamado.lower().split()

In [96]:
tokens

['não',
 'consigo',
 'alterar',
 'minha',
 'senha',
 ',',
 'o',
 'computador',
 'esta',
 'travado',
 ',',
 'preciso',
 'reiniciar',
 '?']

In [97]:
vetores = [embeddings[token] for token in tokens if token in embeddings]

In [98]:
vetores

[array([0.03, 0.93, 0.53]),
 array([0.51, 0.01, 0.91]),
 array([0.01, 0.91, 0.51])]

In [99]:
termos_chaves = [token for token in tokens if token in embeddings]

In [100]:
termos_chaves


['senha', 'travado', 'reiniciar']

In [101]:
vetor_media = np.mean(vetores, axis=0)

In [102]:
vetor_media

array([0.18333333, 0.61666667, 0.65      ])

In [103]:
nivel = np.argmax(vetor_media)

In [104]:
nivel


np.int64(2)

In [105]:
tema = prioridade[nivel]
tema

'alta'

In [106]:
print (f"O chamado '{chamado}")
print (f"por contém os termos: '{termos_chaves}'")
print (f"foi classificado como de: '{tema}' prioridade")

O chamado 'Não consigo alterar minha senha , o computador esta travado , preciso reiniciar ?
por contém os termos: '['senha', 'travado', 'reiniciar']'
foi classificado como de: 'alta' prioridade
